### ISSUE TITLE
Protected Initial makes retries very expensive

### ISSUE THREAD

**Issue by DavidSchinazi** [martinduke/quic-version-aliasing#17]
draft-duke-quic-protected-initial-00 uses the HPKE shared_secret in the computation of the Retry Integrity Tag. This means that servers (or load balancers) will need to perform asymmetric cryptography operations in order to send RETRY packets. That's probably too expensive. What's the benefit of using the shared_secret for retries?

**Comment by martinduke** [comment]
The benefit is that Retries are not spoofable anymore, which I agree isn't huge.

I borrowed this from version aliasing, which was all-symmetric and therefore inexpensive. Your two issues together absolutely present an alternative design -- purely v1 Retries (with a different standard key) and no packet length offset.

**Comment by martinduke** [comment]
As we discussed offline, it's actually the public key, which is a lookup, not a crypto operation. So there's no issue, except a typo in Section 9 (Sections 7 and 8 are correct)
