### ISSUE TITLE
Grease packet length?

### ISSUE THREAD

**Issue by martinduke** [martinduke/quic-version-aliasing#2]
We could have each aliased version also be associated with an arbitrary integer that is added to the packet length field in Long Headers.

This has two advantages
(1) Middleboxes can't ossify on certain packet length field signatures (e.g. computing from 1200B Initial Packets) or "help" by checking the length isn't obviously bogus (which would break future attempts to encrypt or move this field)
(2) We could avoid the pain of trial decryption when things go wrong. If the client is bogus or the server has lost all state and is using a new key to generate the salt, the packet length would probably turn out to be obviously wrong. If we don't need to trial decrypt to figure out that we're in that state, that saves cycles and also simplifies some of the current ambiguity in the VA Retry logic.

**Comment by martinthomson** [comment]
Would the addition be done modulo some number?  Maybe modulo 2^6/2^14/2^30/2^62?

**Comment by martinduke** [comment]
If the offset is max (2^61-1), there's no need for modulo addition and assuming a practical MTU of ~2000 would reduce the probability of having to try to decrypt a packet that you can't decrypt to roughly 1/2^49.

**Comment by martinthomson** [comment]
The problem with non-modulo addition is that you increase the size of the encoding, which interferes with packet size calculations.  I suggested the split modulo because you could retain the length that way.

**Comment by martinduke** [comment]
Hmm. Admittedly this is a drawback. In practice most QUIC implementations never have to go over 14 bits, but to get sufficient entropy we'd need at least 30.

The constraint here is that if the server reboots and loses its salt derivation key, it might send a Retry packet if the packet length is valid, and if the salt is wrong but the packet length is OK the integrity check will fail.
