### ISSUE TITLE
Remove Version Negotation section from Protected Initials?

### ISSUE THREAD

**Issue by martinduke** [martinduke/quic-version-aliasing#29]
@DavidSchinazi says:

> I would simply remove this section. Versions are assumed incompatible by default and this doesn't provide anything useful?

I replied:
> But later on, it says that Protected Initials is compatible with version 1. Aren't we supposed to say that when we propose new versions?

Not sure what the right answer is, so I opened this issue

**Comment by DavidSchinazi** [comment]
What's the benefit of marking these two versions as compatible? Do you foresee a use-case where you would want to perform compatible Version negotiation from one to the other?

**Comment by martinduke** [comment]
I'm struggling to find one. I don't feel a desperate need to keep this text, but want to follow whatever formal requirements are necessary regarding declaring compatibility because

(1) we shouldn't get lazy about following the rules before VN is even done yet; and
(2) authors of other new versions may use this as a template.

**Comment by DavidSchinazi** [comment]
My point is that VN is designed so that if you define a new version without saying anything then it's incompatible. Since that's what we want here, I'd rather not say anything. Authors of new versions should do the same and not say anything unless they want to be compatible, which we don't.

**Comment by martinduke** [comment]
Fixed by #32
