### ISSUE TITLE
Are there Version Downgrade Protections?

### ISSUE THREAD

**Issue by martinduke** [martinduke/quic-version-aliasing#30]
As @DavidSchinazi points out, a version downgrade is just like any other version of QUIC, so it's not all that unique.

OTOH, since 100% of the value of these versions occurs in the Initial, before we can validate version negotiation, there are unique attacks and unique considerations. I'm inclined to leave it in but this issue can capture the discussion.

**Comment by DavidSchinazi** [comment]
I see what you're saying, if the client receives VN and restarts with QUICv1 we need that to fail. I would suggest we instead just say that the if a client receives VN, it MUST fail the connection and not restart on a different version unless it has a downgrade-prevention mechanism such as draft-ietf-quic-version-negotiation. That way if it has that draft it works, and if someone builds a better VN later we can also use it.

**Comment by martinduke** [comment]
Oops, some text I wanted in here was lost in the cut-and-paste from VA. PR to come.

However, I'm just saying you MUST support VN if you multiple versions. Good enough, or would you allow non-support with your text?

**Comment by DavidSchinazi** [comment]
My fundamental point is that the VN draft is *a* way to secure VN, it's not *the* way to secure VN. We shouldn't have a normative requirement to support *that* particular way.
