### ISSUE TITLE
Add Considerations for Numeric Identifiers

### ISSUE THREAD

**Issue by martinduke** [martinduke/quic-version-aliasing#48]
See draft-gont-numeric-ids-sec-considerations.

Prevent servers from doing stupid things, re: Connection ID and Version.

**Comment by DavidSchinazi** [comment]
Isn't this just a matter of saying that random numbers MUST be generated using a secure PRNG?

**Comment by martinduke** [comment]
Yes, after looking again I don't think there's anything to do here.
